# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: api/auth
      refresh: api/refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG